### ISSUE TITLE
خطا به هنگام نصب

### ISSUE THREAD

**Issue by farhadhp** [nimahkh/digiNode#6]
<div dir="rtl">
موقع نصب خطای زیر رو میده.

$ npm install
 npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, fl atted is its successor.                                                          npm ERR! code Z_BUF_ERROR                                                        npm ERR! errno -5                                                                npm ERR! zlib: unexpected end of file
--

ظاهر پکیج  circular-json هم منسوخ شده.
</div>

**Comment by nimahkh** [comment]
<div dir="rtl" align="right">
سلام دوست من . این خط که شما گذاشتید ، یک هشدار یا warning  . 
<br/>
لطفا خطی که Error  هست رو ارسال کنین یا تصویر رو قرار بدید 
<br/>
ممنون 
</div>

**Comment by farhadhp** [comment]
```
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Farhad\AppData\Roaming\npm-cache\_logs\2019-03-30T19_31_52_616Z-debug.log
```

**Comment by nimahkh** [comment]
> ```
> npm ERR! code Z_BUF_ERROR
> npm ERR! errno -5
> npm ERR! zlib: unexpected end of file
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Farhad\AppData\Roaming\npm-cache\_logs\2019-03-30T19_31_52_616Z-debug.log
> ```

``` npm cache clean --force```
<div dir="rtl" align="right">
این دستور رو بزنید و بعد مجدد نصب کنین
</div>
